-- MySQL Script generated by MySQL Workbench
-- Sat 20 Apr 2024 08:58:43 PM AEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chroma_hub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chroma_hub` ;

-- -----------------------------------------------------
-- Schema chroma_hub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chroma_hub` DEFAULT CHARACTER SET utf8 ;
USE `chroma_hub` ;

-- -----------------------------------------------------
-- Table `chroma_hub`.`template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`template` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`template` (
  `templateID` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `layer` INT NOT NULL,
  PRIMARY KEY (`templateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`geometry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`geometry` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`geometry` (
  `geometryID` INT NOT NULL AUTO_INCREMENT,
  `templateID` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`geometryID`),
  INDEX `fk_geometry_template_idx` (`templateID` ASC) VISIBLE,
  CONSTRAINT `fk_geometry_template`
    FOREIGN KEY (`templateID`)
    REFERENCES `chroma_hub`.`template` (`templateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`attribute` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`attribute` (
  `attributeID` INT NOT NULL AUTO_INCREMENT,
  `geometryID` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `visible` TINYINT NOT NULL,
  PRIMARY KEY (`attributeID`),
  INDEX `fk_attribute_geometry1_idx` (`geometryID` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_geometry1`
    FOREIGN KEY (`geometryID`)
    REFERENCES `chroma_hub`.`geometry` (`geometryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
