-- MySQL Script generated by MySQL Workbench
-- Sun 28 Apr 2024 03:18:42 PM AEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chroma_hub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chroma_hub` ;

-- -----------------------------------------------------
-- Schema chroma_hub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chroma_hub` ;
USE `chroma_hub` ;

-- -----------------------------------------------------
-- Table `chroma_hub`.`template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`template` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`template` (
  `templateID` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `layer` INT NOT NULL,
  PRIMARY KEY (`templateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`geometry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`geometry` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`geometry` (
  `geometryID` INT NOT NULL AUTO_INCREMENT,
  `templateID` INT NOT NULL,
  `geo_num` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `geo_type` SMALLINT(1) NOT NULL,
  `prop_type` SMALLINT(1) NOT NULL,
  `rel_x` SMALLINT(1) NOT NULL,
  `rel_y` SMALLINT(1) NOT NULL,
  `parent` INT NOT NULL,
  PRIMARY KEY (`geometryID`, `templateID`),
  INDEX `fk_geometry_template_idx` (`templateID` ASC) VISIBLE,
  CONSTRAINT `fk_geometry_template`
    FOREIGN KEY (`templateID`)
    REFERENCES `chroma_hub`.`template` (`templateID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`rectangle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`rectangle` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`rectangle` (
  `geometryID` INT NOT NULL,
  `width` SMALLINT(1) NOT NULL DEFAULT 0,
  `height` SMALLINT(1) NOT NULL DEFAULT 0,
  `rounding` SMALLINT(1) NOT NULL DEFAULT 0,
  `color` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`geometryID`),
  INDEX `fk_rectangle_geometry1_idx` (`geometryID` ASC) VISIBLE,
  CONSTRAINT `fk_rectangle_geometry1`
    FOREIGN KEY (`geometryID`)
    REFERENCES `chroma_hub`.`geometry` (`geometryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`text` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`text` (
  `geometryID` INT NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  `color` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`geometryID`),
  INDEX `fk_text_geometry1_idx` (`geometryID` ASC) VISIBLE,
  CONSTRAINT `fk_text_geometry1`
    FOREIGN KEY (`geometryID`)
    REFERENCES `chroma_hub`.`geometry` (`geometryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`circle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`circle` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`circle` (
  `geometryID` INT NOT NULL,
  `inner_radius` SMALLINT(1) NOT NULL,
  `outer_radius` SMALLINT(1) NOT NULL,
  `start_angle` SMALLINT(1) NOT NULL,
  `end_angle` SMALLINT(1) NOT NULL,
  `color` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`geometryID`),
  INDEX `fk_circle_geometry1_idx` (`geometryID` ASC) VISIBLE,
  CONSTRAINT `fk_circle_geometry1`
    FOREIGN KEY (`geometryID`)
    REFERENCES `chroma_hub`.`geometry` (`geometryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`list` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`list` (
  `geometryID` INT NOT NULL,
  `row` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`geometryID`),
  CONSTRAINT `fk_list_geometry1`
    FOREIGN KEY (`geometryID`)
    REFERENCES `chroma_hub`.`geometry` (`geometryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`asset` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`asset` (
  `geometryID` INT NOT NULL,
  `directory` VARCHAR(100) NULL,
  `name` VARCHAR(50) NULL,
  `assetID` INT NOT NULL,
  `scale` FLOAT NOT NULL,
  PRIMARY KEY (`geometryID`),
  CONSTRAINT `fk_asset_geometry1`
    FOREIGN KEY (`geometryID`)
    REFERENCES `chroma_hub`.`geometry` (`geometryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`keyframe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`keyframe` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`keyframe` (
  `frameID` INT NOT NULL AUTO_INCREMENT,
  `templateID` INT NOT NULL,
  `frameNum` INT NOT NULL,
  `geoNum` INT NOT NULL,
  `attr` SMALLINT NOT NULL,
  `type` SMALLINT NOT NULL,
  `mask` TINYINT NOT NULL,
  `expand` TINYINT NOT NULL,
  PRIMARY KEY (`frameID`, `templateID`),
  INDEX `fk_keyframe_template1_idx` (`templateID` ASC) VISIBLE,
  CONSTRAINT `fk_keyframe_template1`
    FOREIGN KEY (`templateID`)
    REFERENCES `chroma_hub`.`template` (`templateID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`bindFrame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`bindFrame` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`bindFrame` (
  `frameID` INT NOT NULL,
  `bindFrameID` INT NOT NULL,
  PRIMARY KEY (`frameID`),
  INDEX `fk_bindFrame_keyframe1_idx` (`bindFrameID` ASC) VISIBLE,
  CONSTRAINT `fk_bindFrame_keyframe1`
    FOREIGN KEY (`bindFrameID`)
    REFERENCES `chroma_hub`.`keyframe` (`frameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bindFrame_keyframe2`
    FOREIGN KEY (`frameID`)
    REFERENCES `chroma_hub`.`keyframe` (`frameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`setFrame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`setFrame` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`setFrame` (
  `frameID` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`frameID`),
  CONSTRAINT `fk_table2_keyframe1`
    FOREIGN KEY (`frameID`)
    REFERENCES `chroma_hub`.`keyframe` (`frameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chroma_hub`.`userFrame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chroma_hub`.`userFrame` ;

CREATE TABLE IF NOT EXISTS `chroma_hub`.`userFrame` (
  `frameID` INT NOT NULL,
  PRIMARY KEY (`frameID`),
  CONSTRAINT `fk_userFrame_keyframe1`
    FOREIGN KEY (`frameID`)
    REFERENCES `chroma_hub`.`keyframe` (`frameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
