---
name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with: 
        go-version: 1.22.0

    - name: Setup Environment
      run: |
          sudo apt-get update -qq
          sudo apt-get install libgtk-3-dev 

    # - name: Test Templates 
    #   working-directory: ${{github.workspace}}/hub
    #   run: go test

    - name: Test Pages
      working-directory: ${{github.workspace}}/library/pages
      run: go test

    - name: Test Parser
      working-directory: ${{github.workspace}}/library/parser
      run: go test

